// Mock data — 之後可替換為 Google Sheets API 呼叫

const APP_DATA = {

  kpis: {
    activatedUnits: 6,
    inventoriedUnits: 5,
    pocInProgress: 2,
    liveApplications: 2,
    replicableCases: 2,
    aiChampions: 4,
    savedHours: 248,
    estimatedValue: 186000,
  },

  regions: [
    { name: '台灣',   status: '可複製',    color: 'gold',   dot: '#d97706', units: 4, active: 4 },
    { name: '中國',   status: 'PoC 測試中', color: 'yellow', dot: '#f59e0b', units: 1, active: 1 },
    { name: '東南亞', status: '需求盤點中', color: 'blue',   dot: '#3b82f6', units: 1, active: 1 },
    { name: '美洲',   status: '未啟動',    color: 'gray',   dot: '#94a3b8', units: 1, active: 0 },
    { name: '歐洲',   status: '未啟動',    color: 'gray',   dot: '#94a3b8', units: 1, active: 0 },
  ],

  funnel: [
    { label: '需求蒐集', value: 18, color: '#3b82f6' },
    { label: '篩選案例', value: 12, color: '#6366f1' },
    { label: 'PoC 測試', value: 5,  color: '#f59e0b' },
    { label: '已上線',   value: 2,  color: '#22c55e' },
    { label: '可複製',   value: 2,  color: '#d97706' },
  ],

  units: [
    {
      id: 1, unitName: '企劃室', country: '台灣', factory: '總部',
      aiContact: '林志豪', aiChampion: '林志豪',
      hasAiTalent: true, needSupport: false,
      maturityLevel: 'L5', currentStage: '可複製',
      appTypes: ['自動化', '知識管理', 'API 串接'],
      repCase: 'AI 戰情儀表板', estimatedBenefit: '節省 60% 報告時間',
      nextMilestone: '推廣至其他單位', dueDate: '2026-06-30', lastUpdated: '2026-05-16',
    },
    {
      id: 2, unitName: '台灣製造一廠', country: '台灣', factory: 'TW-F1',
      aiContact: '陳美玲', aiChampion: '陳美玲',
      hasAiTalent: true, needSupport: false,
      maturityLevel: 'L4', currentStage: '已上線',
      appTypes: ['OCR', '品質檢測'],
      repCase: '瓶蓋 OCR 辨識', estimatedBenefit: '節省 40% 人工檢查',
      nextMilestone: '擴大部署至 B 線', dueDate: '2026-06-15', lastUpdated: '2026-05-12',
    },
    {
      id: 3, unitName: '台灣製造三廠', country: '台灣', factory: 'TW-F3',
      aiContact: '王大明', aiChampion: '',
      hasAiTalent: false, needSupport: true,
      maturityLevel: 'L2', currentStage: '需求盤點',
      appTypes: ['OCR', '文件處理'],
      repCase: '調撥單 OCR', estimatedBenefit: '縮短 30% 文件流程',
      nextMilestone: '完成需求確認', dueDate: '2026-05-31', lastUpdated: '2026-04-28',
    },
    {
      id: 4, unitName: '越南廠', country: '越南', factory: 'VN-F1',
      aiContact: 'Nguyen Van A', aiChampion: '',
      hasAiTalent: false, needSupport: true,
      maturityLevel: 'L1', currentStage: '需求盤點',
      appTypes: ['翻譯'],
      repCase: '', estimatedBenefit: '',
      nextMilestone: '進行需求訪談', dueDate: '2026-06-15', lastUpdated: '2026-04-15',
    },
    {
      id: 5, unitName: '中國廠（蘇州）', country: '中國', factory: 'CN-SZ',
      aiContact: '張偉', aiChampion: '張偉',
      hasAiTalent: true, needSupport: false,
      maturityLevel: 'L3', currentStage: 'PoC 測試',
      appTypes: ['資料分析', '自動化'],
      repCase: '生產異常偵測 PoC', estimatedBenefit: '降低 20% 停線',
      nextMilestone: '完成 PoC 報告', dueDate: '2026-06-30', lastUpdated: '2026-05-08',
    },
    {
      id: 6, unitName: '台灣業務部', country: '台灣', factory: '總部',
      aiContact: '李小雨', aiChampion: '李小雨',
      hasAiTalent: true, needSupport: false,
      maturityLevel: 'L3', currentStage: 'PoC 測試',
      appTypes: ['客服', '知識管理'],
      repCase: '客戶詢問自動回覆', estimatedBenefit: '節省 50% 詢答時間',
      nextMilestone: '完成 A/B 測試', dueDate: '2026-07-15', lastUpdated: '2026-05-14',
    },
    {
      id: 7, unitName: '美洲業務', country: '美國', factory: 'US-Sales',
      aiContact: 'John Smith', aiChampion: '',
      hasAiTalent: false, needSupport: true,
      maturityLevel: 'L0', currentStage: '未啟動',
      appTypes: [],
      repCase: '', estimatedBenefit: '',
      nextMilestone: '安排初次說明會', dueDate: '2026-07-31', lastUpdated: '',
    },
    {
      id: 8, unitName: '歐洲業務', country: '德國', factory: 'EU-Sales',
      aiContact: '', aiChampion: '',
      hasAiTalent: false, needSupport: true,
      maturityLevel: 'L0', currentStage: '未啟動',
      appTypes: [],
      repCase: '', estimatedBenefit: '',
      nextMilestone: '確認聯絡窗口', dueDate: '', lastUpdated: '',
    },
  ],

  cases: [
    {
      id: 1, caseName: '瓶蓋外觀 OCR 辨識',
      unitName: '台灣製造一廠', country: '台灣', factory: 'TW-F1',
      appType: 'OCR', toolsUsed: ['PaddleOCR', 'Python', 'Cloud Run'],
      problem: '人工目視檢查效率低，漏判率高',
      solution: '使用 PaddleOCR 辨識瓶蓋印字，自動判斷不良品',
      stage: '已上線',
      estimatedBenefit: '節省 40% 人工檢查時間',
      actualBenefit: '每月節省 120 工時，漏判率降低 65%',
      isReplicable: true,
      replicableTo: ['台灣製造三廠', '越南廠'],
      owner: '陳美玲', lastUpdated: '2026-05-12',
    },
    {
      id: 2, caseName: 'AI 推廣戰情儀表板',
      unitName: '企劃室', country: '台灣', factory: '總部',
      appType: '系統整合', toolsUsed: ['Claude API', 'JavaScript', 'Google Sheets'],
      problem: '集團 AI 推廣進度分散，高層難以快速掌握全貌',
      solution: '建立統一儀表板，整合各單位資料並視覺化呈現推廣狀態',
      stage: '已上線',
      estimatedBenefit: '節省 60% 報告製作時間',
      actualBenefit: '每週節省 8 工時，報告品質提升',
      isReplicable: true,
      replicableTo: ['集團其他單位'],
      owner: '林志豪', lastUpdated: '2026-05-16',
    },
    {
      id: 3, caseName: '調撥單 OCR 辨識系統',
      unitName: '台灣製造三廠', country: '台灣', factory: 'TW-F3',
      appType: 'OCR', toolsUsed: ['PaddleOCR', 'Cloud Run', 'GitHub Pages'],
      problem: '調撥單需人工輸入 ERP，耗時且易出錯',
      solution: '拍照上傳自動 OCR，輸出結構化資料供 ERP 匯入',
      stage: '導入中',
      estimatedBenefit: '縮短 30% 文件處理流程',
      actualBenefit: '待確認（預計 2026-06 量化）',
      isReplicable: true,
      replicableTo: ['越南廠', '中國廠（蘇州）'],
      owner: '王大明', lastUpdated: '2026-04-28',
    },
    {
      id: 4, caseName: '生產數據異常偵測 PoC',
      unitName: '中國廠（蘇州）', country: '中國', factory: 'CN-SZ',
      appType: '資料分析', toolsUsed: ['Python', 'BigQuery', 'GCP'],
      problem: '生產線異常難以提前預警，導致非計畫停線',
      solution: '分析歷史感測器數據，建立異常預測模型',
      stage: 'PoC 測試',
      estimatedBenefit: '降低 20% 異常停線次數',
      actualBenefit: '測試中，尚未量化',
      isReplicable: false,
      replicableTo: [],
      owner: '張偉', lastUpdated: '2026-05-08',
    },
    {
      id: 5, caseName: '客戶詢問 AI 自動回覆',
      unitName: '台灣業務部', country: '台灣', factory: '總部',
      appType: '客服', toolsUsed: ['GPT-4o', 'n8n', 'Google Sheets'],
      problem: '業務重複回答常見客戶問題，佔用大量工時',
      solution: '建立 AI 知識庫，自動草擬回覆，業務確認後發送',
      stage: 'PoC 測試',
      estimatedBenefit: '節省 50% 業務詢答時間',
      actualBenefit: '測試中，回覆準確率約 78%',
      isReplicable: false,
      replicableTo: [],
      owner: '李小雨', lastUpdated: '2026-05-14',
    },
  ],

  talents: [
    {
      id: 1, name: '林志豪', unit: '企劃室', country: '台灣',
      role: '開發者',
      skills: ['Claude API', 'JavaScript', 'GCP', 'Workflow', 'OCR'],
      completedProjects: 3, advancedEligible: true, canSupportOthers: true,
      currentCases: ['AI 戰情儀表板', 'OCR 系統整合'],
    },
    {
      id: 2, name: '陳美玲', unit: '台灣製造一廠', country: '台灣',
      role: 'AI Champion',
      skills: ['OCR', 'Python', '品質管理'],
      completedProjects: 2, advancedEligible: true, canSupportOthers: true,
      currentCases: ['瓶蓋 OCR 辨識'],
    },
    {
      id: 3, name: '張偉', unit: '中國廠（蘇州）', country: '中國',
      role: '推動者',
      skills: ['Python', '資料分析', 'BigQuery'],
      completedProjects: 1, advancedEligible: true, canSupportOthers: false,
      currentCases: ['生產異常偵測 PoC'],
    },
    {
      id: 4, name: '李小雨', unit: '台灣業務部', country: '台灣',
      role: 'AI Champion',
      skills: ['GPT', 'Workflow', 'n8n', '知識管理'],
      completedProjects: 1, advancedEligible: false, canSupportOthers: false,
      currentCases: ['客戶詢問自動回覆'],
    },
  ],

  proposals: [
    {
      id: 1, unit: '越南廠', applicant: 'Nguyen Van A',
      problem: '越南廠內部文件多為越文，台灣總部溝通費時，翻譯人力不足，影響跨廠協作效率',
      expectedBenefit: '縮短 50% 跨語言溝通時間',
      status: '評估中', priority: 'medium',
      submittedDate: '2026-04-15', assignedTo: '林志豪',
    },
    {
      id: 2, unit: '美洲業務', applicant: 'John Smith',
      problem: '每月報表需手動彙整 5 個系統的資料，耗費 2 個工作天，且容易出錯',
      expectedBenefit: '節省 80% 報表製作時間',
      status: '已送出', priority: 'high',
      submittedDate: '2026-05-10', assignedTo: '',
    },
    {
      id: 3, unit: '台灣製造三廠', applicant: '王大明',
      problem: '採購合約審閱需法務人力，等待時間長，影響採購週期',
      expectedBenefit: '縮短 40% 合約審閱週期',
      status: '待媒合', priority: 'medium',
      submittedDate: '2026-05-05', assignedTo: '',
    },
  ],

  training: [
    { id: 1, module: 'AI Workflow 自動化', desc: '使用 n8n / Make 建立自動化流程，無需寫程式', icon: '⚡', enrolled: 8, capacity: 12, status: '招生中', nextDate: '2026-06-10' },
    { id: 2, module: 'API 串接實作',       desc: '串接 GPT / Claude API，建立實用 AI 工具',   icon: '🔌', enrolled: 5, capacity: 8,  status: '規劃中', nextDate: '2026-07-01' },
    { id: 3, module: 'AI Agent 開發',      desc: '建立可自主決策的 AI Agent，處理複雜流程',    icon: '🤖', enrolled: 3, capacity: 6,  status: '規劃中', nextDate: '2026-07-15' },
    { id: 4, module: '知識庫整合',          desc: '建立企業內部 AI 知識庫，提升資訊檢索效率',    icon: '📚', enrolled: 6, capacity: 10, status: '招生中', nextDate: '2026-06-20' },
    { id: 5, module: 'AI 專案實作',         desc: '從需求分析到上線，完整 AI 專案開發流程',      icon: '🚀', enrolled: 4, capacity: 8,  status: '規劃中', nextDate: '2026-08-01' },
    { id: 6, module: '系統整合實戰',        desc: 'AI 與 ERP / 現有系統串接實際案例演練',        icon: '🔧', enrolled: 2, capacity: 8,  status: '規劃中', nextDate: '2026-08-15' },
  ],

  executiveItems: [
    { item: '授權採購 AI 工具年度預算',          status: '待決策', priority: 'high' },
    { item: '開放生產數據使用權限（蘇州廠）',      status: '待決策', priority: 'high' },
    { item: '指定越南廠 AI 推動窗口',             status: '進行中', priority: 'medium' },
    { item: '建立正式 AI Champion 職稱與激勵機制', status: '已批准', priority: 'low' },
    { item: '跨部門 AI 資源媒合機制建立',          status: '進行中', priority: 'medium' },
  ],

  updates: [
    { text: '台灣製造一廠 瓶蓋 OCR 上線，月節省 120 工時', date: '2026-05-12' },
    { text: '台灣業務部 客服 AI 進入 A/B 測試',            date: '2026-05-14' },
    { text: '中國蘇州廠 異常偵測 PoC 正式啟動',            date: '2026-05-08' },
    { text: '越南廠翻譯需求提案已收到，評估中',             date: '2026-04-15' },
    { text: '企劃室 AI 戰情儀表板正式上線',                date: '2026-05-16' },
  ],
};
