// Mock data — 可由 Google Sheets 覆蓋

const APP_DATA = {

  // ── 地區 ──
  regions: [
    { name: '台灣',     group: '台灣',     color: 'gold'   },
    { name: '蘇宏總部', group: '中國宏全', color: 'yellow' },
    { name: '清新廠',   group: '中國宏全', color: 'gray'   },
    { name: '漳州廠',   group: '中國宏全', color: 'gray'   },
    { name: '越南',     group: '東南亞總部', color: 'blue'   },
    { name: '泰國',     group: '東南亞總部', color: 'lblue'  },
    { name: '馬來西亞', group: '東南亞總部', color: 'gray'   },
    { name: '緬甸',     group: '東南亞總部', color: 'gray'   },
    { name: '印尼',     group: '東南亞總部', color: 'gray'   },
  ],

  // ── 單位 ──
  units: [
    {
      id: 1, unitName: '企劃室', region: '台灣', factory: '總部',
      aiContact: '林志豪', aiStaff: '林志豪', needSupport: false,
      maturityLevel: 'L5',
      pocItems: ['AI 戰情儀表板', 'OCR 整合工具'],
      estimatedBenefit: '節省 60% 報告時間',
      dueDate: '2026-06-30', lastUpdated: '2026-05-16',
    },
    {
      id: 2, unitName: '台灣製造一廠', region: '台灣', factory: 'TW-F1',
      aiContact: '陳美玲', aiStaff: '陳美玲', needSupport: false,
      maturityLevel: 'L4',
      pocItems: ['瓶蓋 OCR 辨識'],
      estimatedBenefit: '節省 40% 人工檢查',
      dueDate: '2026-06-15', lastUpdated: '2026-05-12',
    },
    {
      id: 3, unitName: '台灣製造三廠', region: '台灣', factory: 'TW-F3',
      aiContact: '王大明', aiStaff: '', needSupport: true,
      maturityLevel: 'L2',
      pocItems: ['調撥單 OCR'],
      estimatedBenefit: '縮短 30% 文件流程',
      dueDate: '2026-05-31', lastUpdated: '2026-04-28',
    },
    {
      id: 4, unitName: '台灣業務部', region: '台灣', factory: '總部',
      aiContact: '李小雨', aiStaff: '李小雨', needSupport: false,
      maturityLevel: 'L3',
      pocItems: ['客戶詢問自動回覆'],
      estimatedBenefit: '節省 50% 詢答時間',
      dueDate: '2026-07-15', lastUpdated: '2026-05-14',
    },
    {
      id: 5, unitName: '蘇宏總部', region: '蘇宏總部', factory: 'CN-SZ',
      aiContact: '張偉', aiStaff: '張偉', needSupport: false,
      maturityLevel: 'L3',
      pocItems: ['生產異常偵測'],
      estimatedBenefit: '降低 20% 停線',
      dueDate: '2026-06-30', lastUpdated: '2026-05-08',
    },
    {
      id: 6, unitName: '清新廠', region: '清新廠', factory: 'CN-QX',
      aiContact: '', aiStaff: '', needSupport: true,
      maturityLevel: 'L0',
      pocItems: [],
      estimatedBenefit: '',
      dueDate: '', lastUpdated: '',
    },
    {
      id: 7, unitName: '漳州廠', region: '漳州廠', factory: 'CN-ZZ',
      aiContact: '', aiStaff: '', needSupport: true,
      maturityLevel: 'L0',
      pocItems: [],
      estimatedBenefit: '',
      dueDate: '', lastUpdated: '',
    },
    {
      id: 8, unitName: '越南廠', region: '越南', factory: 'VN-F1',
      aiContact: 'Nguyen Van A', aiStaff: '', needSupport: true,
      maturityLevel: 'L2',
      pocItems: ['多語言文件翻譯'],
      estimatedBenefit: '縮短 50% 跨語言溝通',
      dueDate: '2026-06-15', lastUpdated: '2026-04-15',
    },
    {
      id: 9, unitName: '泰國廠', region: '泰國', factory: 'TH-F1',
      aiContact: 'Somchai P.', aiStaff: '', needSupport: true,
      maturityLevel: 'L1',
      pocItems: [],
      estimatedBenefit: '',
      dueDate: '', lastUpdated: '2026-04-10',
    },
    {
      id: 10, unitName: '馬來西亞廠', region: '馬來西亞', factory: 'MY-F1',
      aiContact: '', aiStaff: '', needSupport: true,
      maturityLevel: 'L0',
      pocItems: [],
      estimatedBenefit: '',
      dueDate: '', lastUpdated: '',
    },
    {
      id: 11, unitName: '緬甸廠', region: '緬甸', factory: 'MM-F1',
      aiContact: '', aiStaff: '', needSupport: true,
      maturityLevel: 'L0',
      pocItems: [],
      estimatedBenefit: '',
      dueDate: '', lastUpdated: '',
    },
    {
      id: 12, unitName: '印尼廠', region: '印尼', factory: 'ID-F1',
      aiContact: '', aiStaff: '', needSupport: true,
      maturityLevel: 'L0',
      pocItems: [],
      estimatedBenefit: '',
      dueDate: '', lastUpdated: '',
    },
  ],

  // ── AI 應用案例（stage: 'poc' | 'completed'）──
  cases: [
    {
      id: 1, caseName: '瓶蓋外觀 OCR 辨識',
      unitName: '台灣製造一廠', region: '台灣',
      appType: 'OCR', stage: 'completed',
      toolsUsed: ['PaddleOCR', 'Python', 'Cloud Run'],
      architectureNote: 'Cloud Run 部署 PaddleOCR 模型，前端拍照上傳，後端回傳辨識結果與良率判斷',
      problem: '人工目視檢查效率低，漏判率高',
      solution: '使用 PaddleOCR 辨識瓶蓋印字，自動判斷不良品',
      estimatedBenefit: '節省 40% 人工檢查時間',
      actualBenefit: '每月節省 120 工時，漏判率降低 65%',
      isReplicable: true,
      replicableTo: ['台灣製造三廠', '越南廠'],
      owner: '陳美玲', lastUpdated: '2026-05-12',
    },
    {
      id: 2, caseName: 'AI 推廣管理儀表板',
      unitName: '企劃室', region: '台灣',
      appType: '系統整合', stage: 'completed',
      toolsUsed: ['Claude API', 'JavaScript', 'Google Sheets'],
      architectureNote: 'Google Sheets 作為資料庫，靜態前端讀取 Sheets API，GitHub Pages 部署，零後台成本',
      problem: '集團 AI 推廣進度分散，管理與回報困難',
      solution: '統一儀表板整合各單位進度，視覺化呈現成熟度',
      estimatedBenefit: '節省 60% 報告製作時間',
      actualBenefit: '每週節省 8 工時，報告品質提升',
      isReplicable: true,
      replicableTo: ['集團其他單位'],
      owner: '林志豪', lastUpdated: '2026-05-16',
    },
    {
      id: 3, caseName: '調撥單 OCR 辨識',
      unitName: '台灣製造三廠', region: '台灣',
      appType: 'OCR', stage: 'poc',
      toolsUsed: ['PaddleOCR', 'Cloud Run', 'GitHub Pages'],
      architectureNote: '架構同台灣一廠 OCR 系統，可直接複製部署',
      problem: '調撥單需人工輸入 ERP，耗時且易出錯',
      solution: '拍照上傳自動 OCR，輸出結構化資料供 ERP 匯入',
      estimatedBenefit: '縮短 30% 文件處理流程',
      actualBenefit: '測試中',
      isReplicable: true,
      replicableTo: ['越南廠', '中國廠（蘇州）'],
      owner: '王大明', lastUpdated: '2026-04-28',
    },
    {
      id: 4, caseName: '生產數據異常偵測',
      unitName: '中國廠（蘇州）', region: '中國',
      appType: '資料分析', stage: 'poc',
      toolsUsed: ['Python', 'BigQuery', 'GCP'],
      architectureNote: '歷史感測器數據存入 BigQuery，Python 訓練異常偵測模型，GCP Scheduler 排程執行',
      problem: '生產線異常難以提前預警，導致非計畫停線',
      solution: '分析歷史感測器數據建立預測模型，提前發出警報',
      estimatedBenefit: '降低 20% 異常停線次數',
      actualBenefit: '測試中',
      isReplicable: false,
      replicableTo: [],
      owner: '張偉', lastUpdated: '2026-05-08',
    },
    {
      id: 5, caseName: '客戶詢問 AI 自動回覆',
      unitName: '台灣業務部', region: '台灣',
      appType: '客服', stage: 'poc',
      toolsUsed: ['GPT-4o', 'n8n', 'Google Sheets'],
      architectureNote: 'n8n 監聽信件，GPT-4o 依知識庫草擬回覆，業務確認後自動發送',
      problem: '業務重複回答常見客戶問題，佔用大量工時',
      solution: 'AI 知識庫自動草擬回覆，業務審核後送出',
      estimatedBenefit: '節省 50% 業務詢答時間',
      actualBenefit: '測試中，回覆準確率約 78%',
      isReplicable: false,
      replicableTo: [],
      owner: '李小雨', lastUpdated: '2026-05-14',
    },
    {
      id: 6, caseName: '多語言文件翻譯',
      unitName: '越南廠', region: '越南',
      appType: '翻譯', stage: 'poc',
      toolsUsed: ['GPT-4o', 'Google Sheets'],
      architectureNote: '文件上傳後由 GPT-4o 翻譯，輸出越/中/英三語版本',
      problem: '越文文件翻譯人力不足，影響與台灣總部的跨廠溝通',
      solution: 'AI 自動翻譯文件，支援越/中/英',
      estimatedBenefit: '縮短 50% 跨語言溝通時間',
      actualBenefit: '測試中',
      isReplicable: true,
      replicableTo: ['泰國廠', '馬來西亞廠'],
      owner: 'Nguyen Van A', lastUpdated: '2026-05-01',
    },
  ],

  // ── AI 人才 ──
  talents: [
    {
      id: 1, name: '林志豪', unit: '企劃室', region: '台灣',
      role: '開發者', isSeed: true,
      skills: ['Claude API', 'JavaScript', 'GCP', 'n8n', 'OCR'],
      completedCourses: ['AI Workflow 自動化', 'API 串接實作', 'AI Agent 開發'],
      supportScope: '全集團',
    },
    {
      id: 2, name: '陳美玲', unit: '台灣製造一廠', region: '台灣',
      role: 'AI Champion', isSeed: true,
      skills: ['OCR', 'Python', '品質管理'],
      completedCourses: ['AI Workflow 自動化', 'API 串接實作'],
      supportScope: '台灣製造單位',
    },
    {
      id: 3, name: '張偉', unit: '中國廠（蘇州）', region: '中國',
      role: '推動者', isSeed: false,
      skills: ['Python', '資料分析', 'BigQuery'],
      completedCourses: ['AI Workflow 自動化'],
      supportScope: '中國廠區',
    },
    {
      id: 4, name: '李小雨', unit: '台灣業務部', region: '台灣',
      role: 'AI Champion', isSeed: false,
      skills: ['GPT', 'n8n', 'Workflow', '知識管理'],
      completedCourses: ['AI Workflow 自動化'],
      supportScope: '業務單位',
    },
  ],

  // ── 課程安排 ──
  training: [
    {
      id: 1, module: 'AI Workflow 自動化',
      desc: '使用 n8n / Make 建立自動化流程，無需寫程式',
      icon: '⚡', date: '2026-06-10', enrolled: 8, capacity: 12,
      status: '招生中',
      participants: ['林志豪', '陳美玲', '張偉', '李小雨'],
    },
    {
      id: 2, module: 'API 串接實作',
      desc: '串接 GPT / Claude API，建立實用 AI 工具',
      icon: '🔌', date: '2026-07-01', enrolled: 5, capacity: 8,
      status: '規劃中',
      participants: ['林志豪', '陳美玲'],
    },
    {
      id: 3, module: 'AI Agent 開發',
      desc: '建立可自主決策的 AI Agent，處理複雜流程',
      icon: '🤖', date: '2026-07-15', enrolled: 3, capacity: 6,
      status: '規劃中',
      participants: ['林志豪'],
    },
    {
      id: 4, module: '知識庫整合',
      desc: '建立企業內部 AI 知識庫，提升資訊檢索效率',
      icon: '📚', date: '2026-06-20', enrolled: 6, capacity: 10,
      status: '招生中',
      participants: ['林志豪', '李小雨'],
    },
    {
      id: 5, module: 'AI 專案實作',
      desc: '從需求分析到上線，完整 AI 專案開發流程',
      icon: '🚀', date: '2026-08-01', enrolled: 4, capacity: 8,
      status: '規劃中',
      participants: [],
    },
  ],

  // ── 最新動態 ──
  updates: [
    { text: '台灣製造一廠 瓶蓋 OCR 正式上線，月節省 120 工時', date: '2026-05-12' },
    { text: '台灣業務部 客服 AI 進入 A/B 測試', date: '2026-05-14' },
    { text: '中國蘇州廠 異常偵測 PoC 正式啟動', date: '2026-05-08' },
    { text: '越南廠多語言翻譯 PoC 開始測試', date: '2026-05-01' },
    { text: 'AI 推廣管理儀表板 v2.0 上線', date: '2026-05-16' },
  ],
};

// ── L 等級定義（對齊規劃書）──
const MATURITY_LEVELS = {
  L0: { label: '未啟動', desc: '尚未完成資訊普查',           color: '#94a3b8' },
  L1: { label: '已接觸', desc: '已有負責窗口',               color: '#93c5fd' },
  L2: { label: '已提出', desc: '已提出希望解決的問題與目標',  color: '#60a5fa' },
  L3: { label: 'PoC',   desc: '專案開始測試與場域驗證',      color: '#f59e0b' },
  L4: { label: '已成效', desc: '已完成上線測試',              color: '#22c55e' },
  L5: { label: '可複製', desc: '完成後確定可以複製推廣',      color: '#d97706' },
};
